export const TOURNAMENT_STATUS = {
  DRAFT: 'DRAFT',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  ARCHIVED: 'ARCHIVED'
};

export const MATCH_STATUS = {
  DRAFT: 'DRAFT',
  EDITING: 'EDITING',
  COMPLETED: 'COMPLETED'
};
